services:
  geoserver:
    image: kartoza/geoserver:2.26.1
    environment:
      - GEOSERVER_ADMIN_USER=${GEOSERVER_ADMIN_USERNAME}
      - GEOSERVER_ADMIN_PASSWORD=${GEOSERVER_ADMIN_PASSWORD}
    ports:
      - "8080:8080"
    networks:
      - geoserver_network

  nginx:
    image: nginx:latest
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./fullchain.pem:/etc/nginx/fullchain.pem
      - ./privkey.pem:/etc/nginx/privkey.pem
    depends_on:
      - geoserver
    networks:
      - geoserver_network

networks:
  geoserver_network:
    driver: bridge