version: '3.8'

services:
  geoserver:
    image: kartoza/geoserver:2.26.1
    environment:
      - GEOSERVER_ADMIN_USER=${GEOSERVER_ADMIN_USERNAME}
      - GEOSERVER_ADMIN_PASSWORD=${GEOSERVER_ADMIN_PASSWORD}
    ports:
      - "8080:8080"
    networks:
      - geoserver_network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - geoserver
    networks:
      - geoserver_network

networks:
  geoserver_network:
    driver: bridge
