services:
  geoserver:
    image: docker.osgeo.org/geoserver:2.26.0
    ports:
      - "8080:8080"
    networks:
      - geoserver_network

  nginx:
    image: nginx:latest
    container_name: nginx_container
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt/live/geoafrikana.name.ng/fullchain.pem:/etc/nginx/fullchain.pem
      - /etc/letsencrypt/live/geoafrikana.name.ng/privkey.pem:/etc/nginx/privkey.pem
    depends_on:
      - geoserver
    networks:
      - geoserver_network

networks:
  geoserver_network:
    driver: bridge